//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ScannerNAV.Webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ScannerInterface_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class ScannerInterface : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CountPalletOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourcesInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrinterGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetZoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback MovePalletOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetResourcesInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback WrapPalletOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePalletOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPalletToPushOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemovePalletFromPushOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ScannerInterface() {
            this.Url = "http://10.100.3.26:7147/OPC/WS/OPC/Codeunit/ScannerInterface";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CountPalletCompletedEventHandler CountPalletCompleted;
        
        /// <remarks/>
        public event GetResourcesCompletedEventHandler GetResourcesCompleted;
        
        /// <remarks/>
        public event GetResourcesInfoCompletedEventHandler GetResourcesInfoCompleted;
        
        /// <remarks/>
        public event GetPrinterGroupCompletedEventHandler GetPrinterGroupCompleted;
        
        /// <remarks/>
        public event GetZoneCompletedEventHandler GetZoneCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event MovePalletCompletedEventHandler MovePalletCompleted;
        
        /// <remarks/>
        public event SetResourcesInfoCompletedEventHandler SetResourcesInfoCompleted;
        
        /// <remarks/>
        public event WrapPalletCompletedEventHandler WrapPalletCompleted;
        
        /// <remarks/>
        public event CreatePalletCompletedEventHandler CreatePalletCompleted;
        
        /// <remarks/>
        public event AddPalletToPushCompletedEventHandler AddPalletToPushCompleted;
        
        /// <remarks/>
        public event RemovePalletFromPushCompletedEventHandler RemovePalletFromPushCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:CountPallet", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="CountPallet_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CountPallet(ref default_root responseXML, string resourceNo, string palletID, string bin) {
            object[] results = this.Invoke("CountPallet", new object[] {
                        responseXML,
                        resourceNo,
                        palletID,
                        bin});
            responseXML = ((default_root)(results[0]));
        }
        
        /// <remarks/>
        public void CountPalletAsync(default_root responseXML, string resourceNo, string palletID, string bin) {
            this.CountPalletAsync(responseXML, resourceNo, palletID, bin, null);
        }
        
        /// <remarks/>
        public void CountPalletAsync(default_root responseXML, string resourceNo, string palletID, string bin, object userState) {
            if ((this.CountPalletOperationCompleted == null)) {
                this.CountPalletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountPalletOperationCompleted);
            }
            this.InvokeAsync("CountPallet", new object[] {
                        responseXML,
                        resourceNo,
                        palletID,
                        bin}, this.CountPalletOperationCompleted, userState);
        }
        
        private void OnCountPalletOperationCompleted(object arg) {
            if ((this.CountPalletCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountPalletCompleted(this, new CountPalletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:GetResources", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="GetResources_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetResources(ref resource_root responseXML) {
            object[] results = this.Invoke("GetResources", new object[] {
                        responseXML});
            responseXML = ((resource_root)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourcesAsync(resource_root responseXML) {
            this.GetResourcesAsync(responseXML, null);
        }
        
        /// <remarks/>
        public void GetResourcesAsync(resource_root responseXML, object userState) {
            if ((this.GetResourcesOperationCompleted == null)) {
                this.GetResourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourcesOperationCompleted);
            }
            this.InvokeAsync("GetResources", new object[] {
                        responseXML}, this.GetResourcesOperationCompleted, userState);
        }
        
        private void OnGetResourcesOperationCompleted(object arg) {
            if ((this.GetResourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourcesCompleted(this, new GetResourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:GetResourcesInfo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="GetResourcesInfo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetResourcesInfo(ref resource_root responseXML, string resourceNo) {
            object[] results = this.Invoke("GetResourcesInfo", new object[] {
                        responseXML,
                        resourceNo});
            responseXML = ((resource_root)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourcesInfoAsync(resource_root responseXML, string resourceNo) {
            this.GetResourcesInfoAsync(responseXML, resourceNo, null);
        }
        
        /// <remarks/>
        public void GetResourcesInfoAsync(resource_root responseXML, string resourceNo, object userState) {
            if ((this.GetResourcesInfoOperationCompleted == null)) {
                this.GetResourcesInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourcesInfoOperationCompleted);
            }
            this.InvokeAsync("GetResourcesInfo", new object[] {
                        responseXML,
                        resourceNo}, this.GetResourcesInfoOperationCompleted, userState);
        }
        
        private void OnGetResourcesInfoOperationCompleted(object arg) {
            if ((this.GetResourcesInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourcesInfoCompleted(this, new GetResourcesInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:GetPrinterGroup", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="GetPrinterGroup_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetPrinterGroup(ref printergroup_root responseXML) {
            object[] results = this.Invoke("GetPrinterGroup", new object[] {
                        responseXML});
            responseXML = ((printergroup_root)(results[0]));
        }
        
        /// <remarks/>
        public void GetPrinterGroupAsync(printergroup_root responseXML) {
            this.GetPrinterGroupAsync(responseXML, null);
        }
        
        /// <remarks/>
        public void GetPrinterGroupAsync(printergroup_root responseXML, object userState) {
            if ((this.GetPrinterGroupOperationCompleted == null)) {
                this.GetPrinterGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrinterGroupOperationCompleted);
            }
            this.InvokeAsync("GetPrinterGroup", new object[] {
                        responseXML}, this.GetPrinterGroupOperationCompleted, userState);
        }
        
        private void OnGetPrinterGroupOperationCompleted(object arg) {
            if ((this.GetPrinterGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrinterGroupCompleted(this, new GetPrinterGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:GetZone", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="GetZone_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetZone(ref zone_root responseXML) {
            object[] results = this.Invoke("GetZone", new object[] {
                        responseXML});
            responseXML = ((zone_root)(results[0]));
        }
        
        /// <remarks/>
        public void GetZoneAsync(zone_root responseXML) {
            this.GetZoneAsync(responseXML, null);
        }
        
        /// <remarks/>
        public void GetZoneAsync(zone_root responseXML, object userState) {
            if ((this.GetZoneOperationCompleted == null)) {
                this.GetZoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetZoneOperationCompleted);
            }
            this.InvokeAsync("GetZone", new object[] {
                        responseXML}, this.GetZoneOperationCompleted, userState);
        }
        
        private void OnGetZoneOperationCompleted(object arg) {
            if ((this.GetZoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetZoneCompleted(this, new GetZoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:Login", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="Login_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Login(ref default_root responseXML, string resourceNo, int pIN) {
            object[] results = this.Invoke("Login", new object[] {
                        responseXML,
                        resourceNo,
                        pIN});
            responseXML = ((default_root)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(default_root responseXML, string resourceNo, int pIN) {
            this.LoginAsync(responseXML, resourceNo, pIN, null);
        }
        
        /// <remarks/>
        public void LoginAsync(default_root responseXML, string resourceNo, int pIN, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        responseXML,
                        resourceNo,
                        pIN}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:MovePallet", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="MovePallet_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MovePallet(ref default_root responseXML, string resourceNo, string palletID, string newBin) {
            object[] results = this.Invoke("MovePallet", new object[] {
                        responseXML,
                        resourceNo,
                        palletID,
                        newBin});
            responseXML = ((default_root)(results[0]));
        }
        
        /// <remarks/>
        public void MovePalletAsync(default_root responseXML, string resourceNo, string palletID, string newBin) {
            this.MovePalletAsync(responseXML, resourceNo, palletID, newBin, null);
        }
        
        /// <remarks/>
        public void MovePalletAsync(default_root responseXML, string resourceNo, string palletID, string newBin, object userState) {
            if ((this.MovePalletOperationCompleted == null)) {
                this.MovePalletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMovePalletOperationCompleted);
            }
            this.InvokeAsync("MovePallet", new object[] {
                        responseXML,
                        resourceNo,
                        palletID,
                        newBin}, this.MovePalletOperationCompleted, userState);
        }
        
        private void OnMovePalletOperationCompleted(object arg) {
            if ((this.MovePalletCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MovePalletCompleted(this, new MovePalletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:SetResourcesInfo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="SetResourcesInfo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetResourcesInfo(ref default_root responseXML, string resourceNo, bool pickAll, string zone, string printergorup) {
            object[] results = this.Invoke("SetResourcesInfo", new object[] {
                        responseXML,
                        resourceNo,
                        pickAll,
                        zone,
                        printergorup});
            responseXML = ((default_root)(results[0]));
        }
        
        /// <remarks/>
        public void SetResourcesInfoAsync(default_root responseXML, string resourceNo, bool pickAll, string zone, string printergorup) {
            this.SetResourcesInfoAsync(responseXML, resourceNo, pickAll, zone, printergorup, null);
        }
        
        /// <remarks/>
        public void SetResourcesInfoAsync(default_root responseXML, string resourceNo, bool pickAll, string zone, string printergorup, object userState) {
            if ((this.SetResourcesInfoOperationCompleted == null)) {
                this.SetResourcesInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetResourcesInfoOperationCompleted);
            }
            this.InvokeAsync("SetResourcesInfo", new object[] {
                        responseXML,
                        resourceNo,
                        pickAll,
                        zone,
                        printergorup}, this.SetResourcesInfoOperationCompleted, userState);
        }
        
        private void OnSetResourcesInfoOperationCompleted(object arg) {
            if ((this.SetResourcesInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetResourcesInfoCompleted(this, new SetResourcesInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:WrapPallet", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="WrapPallet_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WrapPallet(ref wraptype_root responseXML, string resourceNo, string palletID, string wrapStartTxt, bool doPrint, string wrapTypeTxt) {
            object[] results = this.Invoke("WrapPallet", new object[] {
                        responseXML,
                        resourceNo,
                        palletID,
                        wrapStartTxt,
                        doPrint,
                        wrapTypeTxt});
            responseXML = ((wraptype_root)(results[0]));
        }
        
        /// <remarks/>
        public void WrapPalletAsync(wraptype_root responseXML, string resourceNo, string palletID, string wrapStartTxt, bool doPrint, string wrapTypeTxt) {
            this.WrapPalletAsync(responseXML, resourceNo, palletID, wrapStartTxt, doPrint, wrapTypeTxt, null);
        }
        
        /// <remarks/>
        public void WrapPalletAsync(wraptype_root responseXML, string resourceNo, string palletID, string wrapStartTxt, bool doPrint, string wrapTypeTxt, object userState) {
            if ((this.WrapPalletOperationCompleted == null)) {
                this.WrapPalletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWrapPalletOperationCompleted);
            }
            this.InvokeAsync("WrapPallet", new object[] {
                        responseXML,
                        resourceNo,
                        palletID,
                        wrapStartTxt,
                        doPrint,
                        wrapTypeTxt}, this.WrapPalletOperationCompleted, userState);
        }
        
        private void OnWrapPalletOperationCompleted(object arg) {
            if ((this.WrapPalletCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WrapPalletCompleted(this, new WrapPalletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:CreatePallet", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="CreatePallet_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreatePallet(ref default_root scannerResponseDefault, string _PalletID, string _Barcode, decimal _Quantity) {
            object[] results = this.Invoke("CreatePallet", new object[] {
                        scannerResponseDefault,
                        _PalletID,
                        _Barcode,
                        _Quantity});
            scannerResponseDefault = ((default_root)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePalletAsync(default_root scannerResponseDefault, string _PalletID, string _Barcode, decimal _Quantity) {
            this.CreatePalletAsync(scannerResponseDefault, _PalletID, _Barcode, _Quantity, null);
        }
        
        /// <remarks/>
        public void CreatePalletAsync(default_root scannerResponseDefault, string _PalletID, string _Barcode, decimal _Quantity, object userState) {
            if ((this.CreatePalletOperationCompleted == null)) {
                this.CreatePalletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePalletOperationCompleted);
            }
            this.InvokeAsync("CreatePallet", new object[] {
                        scannerResponseDefault,
                        _PalletID,
                        _Barcode,
                        _Quantity}, this.CreatePalletOperationCompleted, userState);
        }
        
        private void OnCreatePalletOperationCompleted(object arg) {
            if ((this.CreatePalletCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePalletCompleted(this, new CreatePalletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:AddPalletToPush", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="AddPalletToPush_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddPalletToPush(ref default_root responseXML, string resourceNo, string palletID, string newBin) {
            object[] results = this.Invoke("AddPalletToPush", new object[] {
                        responseXML,
                        resourceNo,
                        palletID,
                        newBin});
            responseXML = ((default_root)(results[0]));
        }
        
        /// <remarks/>
        public void AddPalletToPushAsync(default_root responseXML, string resourceNo, string palletID, string newBin) {
            this.AddPalletToPushAsync(responseXML, resourceNo, palletID, newBin, null);
        }
        
        /// <remarks/>
        public void AddPalletToPushAsync(default_root responseXML, string resourceNo, string palletID, string newBin, object userState) {
            if ((this.AddPalletToPushOperationCompleted == null)) {
                this.AddPalletToPushOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPalletToPushOperationCompleted);
            }
            this.InvokeAsync("AddPalletToPush", new object[] {
                        responseXML,
                        resourceNo,
                        palletID,
                        newBin}, this.AddPalletToPushOperationCompleted, userState);
        }
        
        private void OnAddPalletToPushOperationCompleted(object arg) {
            if ((this.AddPalletToPushCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPalletToPushCompleted(this, new AddPalletToPushCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ScannerInterface:RemovePalletFromPush", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", ResponseElementName="RemovePalletFromPush_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemovePalletFromPush(ref default_root responseXML, string resourceNo, string pushBin) {
            object[] results = this.Invoke("RemovePalletFromPush", new object[] {
                        responseXML,
                        resourceNo,
                        pushBin});
            responseXML = ((default_root)(results[0]));
        }
        
        /// <remarks/>
        public void RemovePalletFromPushAsync(default_root responseXML, string resourceNo, string pushBin) {
            this.RemovePalletFromPushAsync(responseXML, resourceNo, pushBin, null);
        }
        
        /// <remarks/>
        public void RemovePalletFromPushAsync(default_root responseXML, string resourceNo, string pushBin, object userState) {
            if ((this.RemovePalletFromPushOperationCompleted == null)) {
                this.RemovePalletFromPushOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemovePalletFromPushOperationCompleted);
            }
            this.InvokeAsync("RemovePalletFromPush", new object[] {
                        responseXML,
                        resourceNo,
                        pushBin}, this.RemovePalletFromPushOperationCompleted, userState);
        }
        
        private void OnRemovePalletFromPushOperationCompleted(object arg) {
            if ((this.RemovePalletFromPushCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemovePalletFromPushCompleted(this, new RemovePalletFromPushCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class default_root {
        
        private default_response[] default_responseField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("default_response")]
        public default_response[] default_response {
            get {
                return this.default_responseField;
            }
            set {
                this.default_responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class default_response {
        
        private string statusField;
        
        private string status_textField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string status_text {
            get {
                return this.status_textField;
            }
            set {
                this.status_textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class wraptype {
        
        private int wraptype_entrynoField;
        
        private string wraptype_descField;
        
        public wraptype() {
            this.wraptype_entrynoField = 0;
        }
        
        /// <remarks/>
        public int wraptype_entryno {
            get {
                return this.wraptype_entrynoField;
            }
            set {
                this.wraptype_entrynoField = value;
            }
        }
        
        /// <remarks/>
        public string wraptype_desc {
            get {
                return this.wraptype_descField;
            }
            set {
                this.wraptype_descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class wraptype_response {
        
        private string statusField;
        
        private string status_textField;
        
        private string default_wraptypeField;
        
        private wraptype[] wraptypeField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string status_text {
            get {
                return this.status_textField;
            }
            set {
                this.status_textField = value;
            }
        }
        
        /// <remarks/>
        public string default_wraptype {
            get {
                return this.default_wraptypeField;
            }
            set {
                this.default_wraptypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wraptype")]
        public wraptype[] wraptype {
            get {
                return this.wraptypeField;
            }
            set {
                this.wraptypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class wraptype_root {
        
        private wraptype_response[] wraptype_responseField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wraptype_response")]
        public wraptype_response[] wraptype_response {
            get {
                return this.wraptype_responseField;
            }
            set {
                this.wraptype_responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class zone {
        
        private string zone_codeField;
        
        private string zone_descField;
        
        /// <remarks/>
        public string zone_code {
            get {
                return this.zone_codeField;
            }
            set {
                this.zone_codeField = value;
            }
        }
        
        /// <remarks/>
        public string zone_desc {
            get {
                return this.zone_descField;
            }
            set {
                this.zone_descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class zone_response {
        
        private string statusField;
        
        private string status_textField;
        
        private zone[] zoneField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string status_text {
            get {
                return this.status_textField;
            }
            set {
                this.status_textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zone")]
        public zone[] zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class zone_root {
        
        private zone_response[] zone_responseField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zone_response")]
        public zone_response[] zone_response {
            get {
                return this.zone_responseField;
            }
            set {
                this.zone_responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class printer_group {
        
        private string printer_noField;
        
        private string printer_descField;
        
        /// <remarks/>
        public string printer_no {
            get {
                return this.printer_noField;
            }
            set {
                this.printer_noField = value;
            }
        }
        
        /// <remarks/>
        public string printer_desc {
            get {
                return this.printer_descField;
            }
            set {
                this.printer_descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class printergroup_response {
        
        private string statusField;
        
        private string status_textField;
        
        private printer_group[] printer_groupField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string status_text {
            get {
                return this.status_textField;
            }
            set {
                this.status_textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("printer_group")]
        public printer_group[] printer_group {
            get {
                return this.printer_groupField;
            }
            set {
                this.printer_groupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class printergroup_root {
        
        private printergroup_response[] printergroup_responseField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("printergroup_response")]
        public printergroup_response[] printergroup_response {
            get {
                return this.printergroup_responseField;
            }
            set {
                this.printergroup_responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class resource {
        
        private string noField;
        
        private string nameField;
        
        private string distnoField;
        
        private string pickallField;
        
        private string zoneField;
        
        private string printergroupField;
        
        /// <remarks/>
        public string no {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string distno {
            get {
                return this.distnoField;
            }
            set {
                this.distnoField = value;
            }
        }
        
        /// <remarks/>
        public string pickall {
            get {
                return this.pickallField;
            }
            set {
                this.pickallField = value;
            }
        }
        
        /// <remarks/>
        public string zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
            }
        }
        
        /// <remarks/>
        public string printergroup {
            get {
                return this.printergroupField;
            }
            set {
                this.printergroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class resource_response {
        
        private string statusField;
        
        private string status_textField;
        
        private resource[] resourceField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string status_text {
            get {
                return this.status_textField;
            }
            set {
                this.status_textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resource")]
        public resource[] resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ScannerInterface")]
    public partial class resource_root {
        
        private resource_response[] resource_responseField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resource_response")]
        public resource_response[] resource_response {
            get {
                return this.resource_responseField;
            }
            set {
                this.resource_responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CountPalletCompletedEventHandler(object sender, CountPalletCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountPalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CountPalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public default_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((default_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetResourcesCompletedEventHandler(object sender, GetResourcesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resource_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resource_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetResourcesInfoCompletedEventHandler(object sender, GetResourcesInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourcesInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourcesInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resource_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resource_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPrinterGroupCompletedEventHandler(object sender, GetPrinterGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrinterGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrinterGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public printergroup_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((printergroup_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetZoneCompletedEventHandler(object sender, GetZoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetZoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetZoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public zone_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((zone_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public default_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((default_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void MovePalletCompletedEventHandler(object sender, MovePalletCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MovePalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MovePalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public default_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((default_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SetResourcesInfoCompletedEventHandler(object sender, SetResourcesInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetResourcesInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetResourcesInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public default_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((default_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void WrapPalletCompletedEventHandler(object sender, WrapPalletCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WrapPalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WrapPalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wraptype_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wraptype_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CreatePalletCompletedEventHandler(object sender, CreatePalletCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public default_root scannerResponseDefault {
            get {
                this.RaiseExceptionIfNecessary();
                return ((default_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddPalletToPushCompletedEventHandler(object sender, AddPalletToPushCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPalletToPushCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPalletToPushCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public default_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((default_root)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemovePalletFromPushCompletedEventHandler(object sender, RemovePalletFromPushCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemovePalletFromPushCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemovePalletFromPushCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public default_root responseXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((default_root)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591